In [10]:
# List comprehension

l_squares = [x**2 for x in range(0,101)]
l_squares_even = [x**2 for x in range(0,101) if x%2==0]

print(l_squares[:10], l_squares_even[:10], sep='\n')

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
[0, 4, 16, 36, 64, 100, 144, 196, 256, 324]


In [6]:
# generator
def meows():
    i = "meow "
    while True:
        yield i
        i = i * 2

for i in meows():
    print(i)
    if len(i) > 100:
        break

meow 
meow meow 
meow meow meow meow 
meow meow meow meow meow meow meow meow 
meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow 
meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow meow 


In [11]:
# numpy 
import numpy as np
random_normal = np.random.normal(0,1, size=(5,5))
print(random_normal)
random_normal = np.where(random_normal > 0.09, random_normal**2, 42)
print(random_normal)

print(random_normal[:,3])

[[ 0.46819553 -0.41167323 -1.62692503 -0.52134693 -0.71853101]
 [ 0.37863786 -0.90315639  1.70252607  0.37632331 -0.67620753]
 [ 1.07007746 -1.77175359  0.64048833 -0.60232185  0.49021123]
 [-0.45008361  0.34886965  0.0497027   0.43826962 -0.88015125]
 [-2.20387794 -1.15066296  0.49614383 -1.10315806  0.98983107]]
[[ 0.21920706 42.         42.         42.         42.        ]
 [ 0.14336663 42.          2.89859502  0.14161923 42.        ]
 [ 1.14506578 42.          0.4102253  42.          0.24030705]
 [42.          0.12171003 42.          0.19208026 42.        ]
 [42.         42.          0.2461587  42.          0.97976554]]
[42.          0.14161923 42.          0.19208026 42.        ]


## Math

f (x, z, a, b) := y = (4ax² + a) + 3 + σ(z) + (σ(b)²)   

∂y/∂x = 8ax  
∂y/∂z = σ(z) - ( 1 - σ(z) )  
∂y/∂a = 4x² + 1  
∂y/∂b = 2σ(b) * ( σ(b) - ( 1 - σ(b) ) ) = 2σ(b)² - 2σ(b) + 2σ(b)²  


∇f w.r.t [x, z, a, b] = (8ax, σ(z) - ( 1 - σ(z) ), 4x² + 1, 2σ(b)² - 2σ(b) + 2σ(b)²)